### ISSUE TITLE
Veeam v12 with PostgreSQL

### ISSUE THREAD

**Issue by franckcosta** [ovh/private-cloud-provider#125]
As a customer i want to use PostgreSQL with Veeam Backup & Replication.

**Comment by pac-chris** [comment]
Any updates please?

**Comment by franckcosta** [comment]
Hello, yes ETA is end of the month.

**Comment by pac-chris** [comment]
Hi - can we please have an ETA?

**Comment by franckcosta** [comment]
Hello, 
It's live, we will update documentation in the next days.
